name: myGreeting
on: push
jobs:
    greet:
        runs-on: ubuntu-latest
        steps:
            - name: "greet user"
              run: |
               echo "Hello World!"
               echo "Today's date is: $(date)"
               echo "Current user is: $(whoami)"
               echo "Current working directory: $(pwd)"
               echo "Listing files in the current directory:"
               ls -la
